name: Taller DevOps - Pipeline CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  # =================================================================
  # JOB 1: VALIDACIÓN Y CALIDAD
  # =================================================================
  ci:
    name: Build, Security and Quality Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    #  ESTE ES EL BLOQUE NUEVO QUE SACAMOS DE LA PÁGINA:
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: SonarCloud Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        ./mvnw clean verify sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=relic7663 \
          -Dsonar.projectKey=RELIC7663_Proyecto-Devops \
          -Dsonar.branch.name=${{ github.ref_name }} \
          -Dsonar.qualitygate.wait=true

    - name: Trivy FS Scan (Security)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '0'
        severity: 'CRITICAL,HIGH' 

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar
  # =================================================================
  # JOB 2: EMPAQUETADO DOCKER
  # =================================================================
  docker:
    name: Build and Push Docker Image
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: app-jar
        path: target/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/relic7663/spring-petclinic-devops:${{ github.sha }}
          ghcr.io/relic7663/spring-petclinic-devops:latest